---
title: "MeTEor Preprocessing steps"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{MeTEor Preprocessing steps}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r message= FALSE, warning=FALSE}
library(tidyverse)
library(VIM)
library(laeken)
library(MeTEor)

```

```{r read_data}
# read in CSV file
data("raw_example_data")
head(raw_example_data[, 1:8], n = 5)
```

```{r remove_duplicates}
# check if the data contains duplicates
duplicated_rows <- raw_example_data[duplicated(raw_example_data), ]

# drop duplicates
raw_example_data <- raw_example_data[!duplicated(raw_example_data), ]

head(raw_example_data[, 1:8], n = 5)
```

```{r drop}
# reorder columns
raw_example_data <- raw_example_data %>% relocate("time", .before = "metabolite_1")


# drop column measurement_complete since it is not used
raw_example_data <- raw_example_data %>% select(-comp)

head(raw_example_data[, 1:8], n = 5)
```

```{r non_numeric_columns}
# check if all data is numeric
non_numeric_columns <- names(raw_example_data)[!sapply(raw_example_data, is.numeric)]

# in out case we just drop the columns, however editing them by hand is also an option
raw_example_data <- raw_example_data %>% select(-all_of(non_numeric_columns))

head(raw_example_data[, 1:8], n = 5)
```

```{r scale}
# Remove columns with more than 10% NA
raw_example_data <- raw_example_data[, which(colMeans(!is.na(raw_example_data)) > 0.9)]

# transform to numeric
cleaned_data <- raw_example_data %>% mutate_if(is.character, as.numeric)

# Select the numeric columns you want to scale
columns_to_scale <- 5:ncol(cleaned_data)

# Scale the selected numeric columns
cleaned_data[, columns_to_scale] <- scale(cleaned_data[, columns_to_scale])

head(cleaned_data[, 1:8], n = 5)
```

```{r missing_data}
# find columns with missing values
columns_with_missing <- names(cleaned_data)[colSums(is.na(cleaned_data)) > 0]

# impute columns using KNN
data_meta_imputed <- kNN(cleaned_data, numFun = weightedMean, weightDist=TRUE, imp_var = FALSE)

head(data_meta_imputed[, 1:8], n = 5)
```

```{r long}
data_meta_imputed_long <- data_meta_imputed  %>%
  pivot_longer(!c("id", "time", "sex", "treatment"), names_to = "metabolites", values_to = "values") %>%
  relocate(time, .after = id)%>%
  relocate(sex, .after = values)%>%
  relocate(treatment, .after = values)

head(data_meta_imputed_long, n = 5)
```

```{r write}
write.csv(data_meta_imputed_long, file = "data_long.csv", row.names = FALSE )
```
