---
title: "Dynamic report"
output: html_document
params:
  reactive_friedman_RMD: NA
  input_RMD: NA
  data_RMD: NA
---

```{r}
reactive_friedman <- params$reactive_friedman_RMD
input <- params$input_RMD
data <- params$data_RMD
```

```{r}
# Display summary statistics table
datatable(reactive_friedman$summary_stat,
  caption = "Summary statistics",
  options = list(
    searching = FALSE,
    lengthChange = FALSE,
    paging = TRUE
  )
)
```

```{r}
# Display Friedman test results
datatable(reactive_friedman$res_fried,
  caption = "Friedman test",
  options = list(
    searching = FALSE,
    lengthChange = FALSE,
    paging = FALSE
  )
)
```

```{r}
# Display Kendall's W results
datatable(reactive_friedman$res_fried_eff,
  caption = "Kendall's W",
  options = list(
    searching = FALSE,
    lengthChange = FALSE,
    paging = FALSE
  )
)
```



```{r}
# Generate pairwise comparisons with xy positions
pair.ws <- reactive_friedman$pair.ws %>% add_xy_position(x = "time")

# Create the boxplot
boxfried <- data %>%
  filter(metabolites %in% input$id8) %>%
  ggboxplot(x = "time", y = "values", add = "point") +
  stat_pvalue_manual(pair.ws, hide.ns = TRUE) +
  labs(
    subtitle = get_test_label(reactive_friedman$res_fried, detailed = TRUE),
    caption = get_pwc_label(pair.ws)
  ) + theme(
    text = element_text(size = 16),
    panel.grid.major = element_blank(),  # Remove major gridlines
    panel.grid.minor = element_blank(),  # Remove minor gridlines
  )

# Print the plot
print(boxfried)
```

```{r}

```

```{r}

```


