---
title: "Dimensionality Reduction - Tensor Factorization"
output:
  html_document:
    code_folding: "hide"
params:
  df_tcam_RMD: NA
  input_RMD: NA
  catv_RMD: NA
  data_RMD: NA
---

```{r include = FALSE}
df_tcam <- params$df_tcam_RMD
input <- params$input_RMD
catv <- params$catv_RMD
data <- params$data_RMD
```

```{r}
library(shiny)
library(dplyr)
library(tidyr)
library(ggplot2)
library(plotly)
library(factoextra)
library(FactoMineR)
library(purrr)
library(rmarkdown)
library(ggpubr)
library(lubridate)  # If you use date manipulations
```


```{r}
a <- catv

vars <- c("id", "time", a, "metabolites", "values")

# for patients
df <- data %>%
  select(all_of(vars)) %>%
  pivot_wider(
    names_from = c("metabolites", "time"),
    values_from = "values", id_cols = all_of(c("id", a))
  ) %>%
  select(-id)

complete_rows <- complete.cases(df[, -1])

df <- df[complete_rows, ]

res.pca <- prcomp(df[, -1])

dim1 <- input$pcAlong %>% as.integer()
dim2 <- input$pcBlong %>% as.integer()

if (length(unique(as.factor(df[[1]]))) < 2) {
  habillage <- "none"
} else {
  habillage <- as.factor(df[[1]])
}

k <- fviz_pca_ind(res.pca,
  label = "none", # hide individual labels
  axes = c(dim1, dim2),
  habillage = habillage, # color by groups
  # palette = c("#00AFBB", "#E7B800", "#FC4E07"),
  addEllipses = TRUE, # Concentration ellipses
  legend.title = catv
) + theme_apa()

k <- ggplotly(k, tooltip = c("x", "y", "color"))

# Fix für Labels

for (i in 1:length(k$x$data)) {
  if (!is.null(k$x$data[[i]]$name)) {
    k$x$data[[i]]$name <- gsub("\\(", "", str_split(k$x$data[[i]]$name, ",")[[1]][1])
  }
}

k %>% layout(
  plot_bgcolor = "#edeff4",
  paper_bgcolor = "#edeff4",
  fig_bgcolor = "#edeff4",
  legend = list(bgcolor = "#edeff4")
)
```

```{r}
a <- catv

vars <- c("id", "time", a, "metabolites", "values")


df <- data %>%
  select(all_of(vars)) %>%
  pivot_wider(
    names_from = c("metabolites", "time"),
    values_from = "values", id_cols = all_of(c("id", a))
  ) %>%
  select(-id)


complete_rows <- complete.cases(df)

df <- df[complete_rows, ]

res.pca <- PCA(df[, -1], graph = FALSE)

dim1 <- input$pcAlong %>% as.integer()

k <- fviz_contrib(res.pca, choice = "var", axes = dim1, top = 10)
ggplotly(k) %>% layout(
  plot_bgcolor = "#edeff4",
  paper_bgcolor = "#edeff4",
  fig_bgcolor = "#edeff4",
  legend = list(bgcolor = "#edeff4")
)
```


```{r}
a <- catv

vars <- c("id", "time", a, "metabolites", "values")


df <- data %>%
  select(all_of(vars)) %>%
  pivot_wider(
    names_from = c("metabolites", "time"),
    values_from = "values", id_cols = all_of(c("id", a))
  ) %>%
  select(-id)

complete_rows <- complete.cases(df[, -1])

df <- df[complete_rows, ]

pca <- prcomp(df[, -1])

# Scores
scores <- pca$x

dim1 <- input$pcAlong %>% as.integer()
dim2 <- input$pcBlong %>% as.integer()
dim3 <- input$pcClong %>% as.integer()

x <- scores[, dim1]
y <- scores[, dim2]
z <- scores[, dim3]

dt.pltly <- cbind(x, y, z, as.factor(df[[a]])) %>% as.data.frame()
colnames(dt.pltly) <- c("x", "y", "z", a)

legend.titel <- colnames(dt.pltly[a])


# 3D plot
p <- plot_ly(dt.pltly,
  x = ~x, y = ~y, z = ~z, color = ~ ifelse(is.na(dt.pltly[[a]]), "NA", as.character(dt.pltly[[a]])),
  colors = c('#BF382A', '#0C4B8E'),
  type = "scatter3d", mode = "markers"
) %>%
  layout(
    scene = list(
      xaxis = list(title = paste0("PC", dim1[1])),
      yaxis = list(title = paste0("PC", dim2[1])),
      zaxis = list(title = paste0("PC", dim3[1])),
      showlegend = TRUE,
      legend = list(title = list(text = legend.titel))
    ),
    plot_bgcolor = "#edeff4",
    paper_bgcolor = "#edeff4",
    fig_bgcolor   = "#edeff4"
  )
p
```


```{r}
          a <- catv
          vars <- c("id", "time", a, "metabolites", "values")

          d <- data
          d2 <- data
          ids <- c(colnames(d)[5:ncol(d)])

          patients_with_all_timepoints <- d %>%
            group_by(id) %>%
            filter(all(unique(d$time) %in% time)) %>%
            distinct(id)

          ids <- c("id", "time", colnames(d2[5:ncol(d2)]) )

          d.t1 <- d2 %>% pivot_wider(names_from = "metabolites",
                                        values_from = "values", id_cols = ids) %>%
                            select(c(ids))

          d.t1 <- semi_join(d.t1, patients_with_all_timepoints, by = "id")
          d.t1 <- d.t1 %>% filter(time==unique(d$time)[1])


          data.tca <- cbind(df_tcam$data.tca, d.t1) %>% as.data.frame()

          req(input$pcAfc)
          req(input$pcBfc)


          dim1 <- input$pcAfc
          dim2 <- input$pcBfc

          vars.fc <- c(dim1, dim2, a, "id")

          data.tca <- data.tca %>%
                          select(all_of(vars.fc))

          data.tca[,a] <- as.factor(data.tca[,a])
          # a <- "gender"

          color <- "black"
          if (length(unique(data.tca[[a]])) < 2) {
            color <- "black"
          }else
          {
            color <- a
          }
          ~as.factor(dt.pltly[[a]])

          tca.plot <- ggscatter(data.tca, x = dim1, y = dim2,
                                fill  = color,
                                shape = color,
                                # label = "id",
                                # repel = FALSE,
                                # size= 5,
                                #palette = c("#00AFBB", "#E7B800", "#FC4E07"),
                                ellipse = TRUE, mean.point = TRUE,
                                star.plot = F) +
                      geom_hline(yintercept = 0, lty = 2) +
                      geom_vline(xintercept = 0, lty = 2) +
                      theme_apa() + ggtitle("Individuals - TCAM")

          tca.plot <- ggplotly(tca.plot)

          # Fix für Labels

          for (i in 1:length(tca.plot$x$data)){
            if (!is.null(tca.plot$x$data[[i]]$name)){
              tca.plot$x$data[[i]]$name =  gsub("\\(","",str_split(tca.plot$x$data[[i]]$name,",")[[1]][1])
            }
          }

          tca.plot %>% layout(plot_bgcolor  = "#edeff4",
                              paper_bgcolor = "#edeff4",
                              fig_bgcolor   = "#edeff4",
                              legend= list(bgcolor = "#edeff4" ))


```


```{r}
        a <- catv
        d <- data
        d2 <- data
        ids <- c(colnames(d)[5:ncol(d)])
        d <- d %>% select(-c(ids))
        metaname <- unique(d$metabolites)

        # data.tca <- tca(d)
        tca.loadings <- df_tcam$tca.loadings %>% as.data.frame()
        tca.loadings <- cbind(tca.loadings, metaname)
        tca.loadings <- tca.loadings %>% column_to_rownames("metaname")

        col.fac <- c()

        for (i in 1:ncol(tca.loadings)) {

          col.fac[i] <- paste0("FC_", i)

        }

        colnames(tca.loadings) <- df_tcam$col.fac

        req(input$pcAfc)

        dim = input$pcAfc

        tca.loadings.shrt <- tca.loadings %>%
                                select(all_of(dim)) %>%
                                arrange(desc(abs(.))) %>%
                                dplyr::slice(1:15)

         metabolite <-rownames(tca.loadings.shrt)

         tca.loadings.shrt <- cbind(metabolite, tca.loadings.shrt)

         barplot <- ggplot(data=tca.loadings.shrt) +
                            geom_bar(aes(x=.data[[dim]],
                                         y=reorder(metabolite,.data[[dim]])),
                                     fill = "#0072B2",
                                     stat="identity") + theme_apa() +
                            labs(size= "",
                                 x = paste0("Factor loadings: ", dim),
                                 y = "",
                                 title = "")
                            ggplotly(barplot) %>%
                                layout(plot_bgcolor  = "#edeff4",
                                       paper_bgcolor = "#edeff4",
                                       fig_bgcolor   = "#edeff4",
                                       legend= list(bgcolor = "#edeff4" ))


```

```{r}

                a <- catv
                d <- data
                d2 <- data

                ids <- c(colnames(d)[5:ncol(d)])

                patients_with_all_timepoints <- d %>%
                  group_by(id) %>%
                  filter(all(unique(d$time) %in% time)) %>%
                  distinct(id)

                ids <- c("id", "time", colnames(d2[5:ncol(d2)]) )

                d.t1 <- d2 %>% pivot_wider(names_from = "metabolites",
                                           values_from = "values", id_cols = ids) %>%
                  select(c(ids))

                d.t1 <- semi_join(d.t1, patients_with_all_timepoints, by = "id")
                d.t1 <- d.t1 %>% filter(time==unique(d$time)[1])


                data.tca <- cbind(df_tcam$data.tca, d.t1) %>% as.data.frame()


                dim1 <- input$pcAfc
                dim2 <- input$pcBfc
                dim3 <- input$pcCfc

                x <- data.tca[[dim1]]
                y <- data.tca[[dim2]]
                z <- data.tca[[dim3]]

                cat <- as.factor(data.tca[[a]])


                dt.pltly <- cbind(x,y,z, cat) %>% as.data.frame()

                colnames(dt.pltly) <- c("x","y","z",a)

                legend.titel <- colnames(dt.pltly[a])

                # 3D plot

                scene = list(xaxis = list(title = paste0("PC", dim1[1])),
                             yaxis = list(title = paste0("PC", dim2[1])),
                             zaxis = list(title = paste0("PC", dim3[1])),
                             showlegend=TRUE,
                             legend = list(title=list(text = legend.titel)))

                color_factors <- ifelse(is.na(dt.pltly[[a]]), "NA", as.character(dt.pltly[[a]]))

                p <- plot_ly(dt.pltly, x = ~x, y = ~y, z = ~z, color = ~color_factors,
                             colors = c('#BF382A', '#0C4B8E'), type = "scatter3d" , mode = "markers") %>%
                              layout(scene = list(xaxis = list(title = paste0(dim1)),
                                                  yaxis = list(title = paste0(dim2)),
                                                  zaxis = list(title = paste0(dim3)),
                                                  showlegend=TRUE,
                                                  legend = list(title=list(text= legend.titel))),
                                                       plot_bgcolor  = "#edeff4",
                                                       paper_bgcolor = "#edeff4",
                                                       fig_bgcolor   = "#edeff4")

                p



```
