---
title: "Dynamic report"
output: html_document
params:
  n: NA
  prediction_stored_RMD: NA
  input_RMD: NA
---

```{r}
# The `params` object is available in the document.
params$n
prediction_stored <- params$prediction_stored_RMD
input <- params$input_RMD
print(params$prediction_stored)
```

A plot of `params$n` random points.

```{r}
plot(rnorm(params$n), rnorm(params$n))
```

```{r}

print(prediction_stored$computation_done)
print(prediction_stored$rfFit)
print(input$prediction_method)
# Check if prediction is done
```


```{r}
# Check if prediction is done
if (prediction_stored$computation_done) {
  # Depending on the prediction method, extract importance
  if (input$prediction_method == 'XGB') {
    imps <- as.matrix(varImp(prediction_stored$rfFit)$importance, scale=FALSE)
  } else {
    imps <- as.matrix(varImp(prediction_stored$rfFit)$importance)
  }

  # Create a data frame for the important features
  imps_df <- data.frame(Overall = imps)
  feature_imp <- imps_df %>% filter(Overall > 0.1) %>% arrange(desc(Overall)) %>% head(10)
  colnames(feature_imp) <- "importance"
  feature_imp$metabolite_name <- row.names(feature_imp)

  # Store important features (global assignment not necessary in RMarkdown)
  feature_importance_stored <- feature_imp$metabolite_name

  # Create the ggplot object
  p <- ggplot(feature_imp, aes(x = reorder(metabolite_name, importance), y = importance)) +
    geom_bar(stat = "identity", fill = "#0072B2") +
    theme_apa() +
    xlab("Metabolites") +
    coord_flip()

  # Convert ggplot to plotly and customize layout
  ggplotly(p) %>% layout(
    plot_bgcolor = "#edeff4",
    paper_bgcolor = "#edeff4",
    fig_bgcolor = "#edeff4",
    legend = list(bgcolor = "#edeff4")
  )
}
```
