---
title: "Dimensionality Reduction - PCA"
output:
  html_document:
    code_folding: "hide"
params:
  df_pca_RMD: NA
  input_RMD: NA
  catv_RMD: NA
  data_RMD: NA
---

```{r include = FALSE}
df_pca <- params$df_pca_RMD
input <- params$input_RMD
catv <- params$catv_RMD
data <- params$data_RMD
```

```{r}
library(dplyr)
library(tidyr)
library(factoextra)
library(ggplot2)
library(plotly)
library(shiny)
library(rmarkdown)
```


```{r, fig.width=9, warning = FALSE}
res.pca <- prcomp(df_pca)

# Visualize eigenvalues/variances
k <- fviz_screeplot(res.pca, addlabels = TRUE) +
                    theme_apa()

ggplotly(k) %>% layout(plot_bgcolor  = "#edeff4",
                       paper_bgcolor = "#edeff4")
```


```{r, fig.width=10}
a <- catv

vars <- c("id", "time", a, "metabolites", "values")

df <- data %>%
  select(all_of(vars)) %>%
  filter(time %in% input$timepoint) %>%
  select(-time) %>%
  pivot_wider(names_from = "metabolites",
              values_from = "values", id_cols = all_of(c("id", a))) %>%
  select(-id)

# Perform PCA on the data after excluding 'a'
df.pca <- df %>% select(-all_of(a)) %>% prcomp()

# Retrieve the selected principal components for plotting
dim1 <- input$pcA %>% as.integer()
dim2 <- input$pcB %>% as.integer()

# Set habillage based on unique categories in the first column
if (length(unique(as.factor(df[[1]]))) < 2) {
  habillage <- "none"
} else {
  habillage <- as.factor(df[[1]])
}

# Generate PCA scatter plot
k <- fviz_pca_ind(df.pca,
                  label = "none",        # Hide individual labels
                  axes = c(dim1, dim2),  # Use the selected PC dimensions for x and y
                  habillage = habillage, # Color by groups if available
                  addEllipses = TRUE     # Add ellipses around groups
) + theme_apa()

# Convert ggplot object to Plotly for interactivity
k <- ggplotly(k)

# Fix labels in the Plotly object
for (i in 1:length(k$x$data)) {
  if (!is.null(k$x$data[[i]]$name)) {
    k$x$data[[i]]$name <- gsub("\\(", "", str_split(k$x$data[[i]]$name, ",")[[1]][1])
  }
}

# Set layout properties for the plotly object
k %>% layout(
  plot_bgcolor  = "#edeff4",
  paper_bgcolor = "#edeff4",
  legend = list(bgcolor = "#edeff4")
)

```



```{r, fig.width=10}
res.pca <- prcomp(df_pca)

dim1 <- input$pcA %>% as.integer()

# Contributions of variables to PC1
k <- fviz_contrib(res.pca, choice = "var", axes = dim1, top = 10)
ggplotly(k) %>% layout(
  plot_bgcolor  = "#edeff4",
  paper_bgcolor = "#edeff4"
)

```


```{r, fig.width=10}
res.pca <- prcomp(df_pca, scale. = TRUE)

dim2 <- input$pcB %>% as.integer()

# Contributions of variables to PC2
k <- fviz_contrib(res.pca, choice = "var", axes = dim2, top = 10)

# Convert to Plotly
ggplotly(k) %>% layout(
  plot_bgcolor = "#edeff4",
  paper_bgcolor = "#edeff4"
)

```


```{r, fig.width=11}
res.pca <- prcomp(df_pca)

dim1 <- input$pcA %>% as.integer()
dim2 <- input$pcB %>% as.integer()

# Control the transparency of variables using their contributions
k <- fviz_pca_var(res.pca, col.var = "contrib",
                  alpha.var = "contrib",
                  axes = c(dim1, dim2),
                  repel = TRUE) +
          theme_apa() +
          theme(
            panel.background = element_rect(fill = "#edeff4",
                                            colour = NA_character_), # necessary to avoid drawing panel outline
            panel.grid.major = element_blank(), # get rid of major grid
            panel.grid.minor = element_blank(), # get rid of minor grid
            plot.background = element_rect(fill = "#edeff4",
                                           colour = NA_character_), # necessary to avoid drawing plot outline
            legend.background = element_rect(fill = "#edeff4"),
            legend.box.background = element_rect(fill = "#edeff4"),
            legend.key = element_rect(fill = "#edeff4")
          )

plot(k)
```

```{r, fig.width=11}
# Assume `data()` is defined and provides the required dataset
# Replace `catv()` and `input$timepoint` with appropriate selections

# Select the categorical variable for grouping
a <- catv  # This function should return a valid categorical variable

# Prepare the data for PCA
vars <- c("id", "time", a, "metabolites", "values")

df <- data %>%
  select(all_of(vars)) %>%
  filter(time %in% input$timepoint) %>%
  select(-time) %>%
  pivot_wider(names_from = "metabolites", values_from = "values", id_cols = all_of(c("id", a))) %>%
  select(-id)

# Perform PCA
pca <- prcomp(df[,-1], center = TRUE, scale. = TRUE)

# Extract the scores
scores <- pca$x

# Get dimensions for the PCA
dim1 <- input$pcA %>% as.integer()
dim2 <- input$pcB %>% as.integer()
dim3 <- input$pcC %>% as.integer()

# Extract scores for the selected dimensions
x <- scores[, dim1]
y <- scores[, dim2]
z <- scores[, dim3]

# Create a data frame for plotly
dt.pltly <- cbind(x, y, z, as.factor(df[[a]])) %>% as.data.frame()
colnames(dt.pltly) <- c("x", "y", "z", a)

# Define legend title
legend.title <- colnames(dt.pltly[a])

# Create 3D plot using plotly
p <- plot_ly(dt.pltly, 
              x = ~x, 
              y = ~y, 
              z = ~z, 
              color = ~ifelse(is.na(dt.pltly[[a]]), "NA", as.character(dt.pltly[[a]])),
              colors = c('#BF382A', '#0C4B8E'), 
              type = "scatter3d", 
              mode = "markers") %>%
  layout(scene = list(xaxis = list(title = paste0("PC", dim1)),
                      yaxis = list(title = paste0("PC", dim2)),
                      zaxis = list(title = paste0("PC", dim3)),
                      showlegend = TRUE,
                      legend = list(title = list(text = legend.title))),
         plot_bgcolor = "#edeff4",
         paper_bgcolor = "#edeff4")

# Display the plot
p
```



