---
title: "Ridge Plot - Compare time points"
output:
  html_document:
    code_folding: "hide"
params:
  ridgeplot_stored_RMD: NA

---

```{r include = FALSE}
ridgeplot_stored <- params$ridgeplot_stored_RMD
```

```{r}
library(ggplot2)
library(ggridges)
library(dplyr)
library(rmarkdown)
library(purrr)
```

```{r, fig.width=12, fig.height=6}

# Check if the computation is done
if (ridgeplot_stored$computation_done_plot1) {

  # Check if there is data to plot
  if (nrow(ridgeplot_stored$computed_data_plot1) == 0) {
    print("no metaboites selected")
  } else {
    # Create the ridge plot
    ggplot(data= ridgeplot_stored$computed_data_plot1, aes(x = values, y = metabolites, fill = time)) +
      geom_density_ridges(alpha = 0.3, scale = 1) +
      theme_ridges() +
      theme(
        panel.background = element_rect(fill = "#edeff4", colour = NA), # Avoid drawing panel outline
        panel.grid.major = element_blank(),  # Remove major gridlines
        panel.grid.minor = element_blank(),  # Remove minor gridlines
        plot.background = element_rect(fill = "#edeff4", colour = NA),  # Avoid drawing plot outline
        legend.background = element_rect(fill = "#edeff4"),
        legend.box.background = element_rect(fill = "#edeff4"),
        legend.key = element_rect(fill = "#edeff4")
      )
  }
}

```
